name: Build and deploy Node.js app to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-server:
    runs-on: windows-latest
    env:
      HOST: ${{ vars.HOST }}
      SMPT_SERVER: ${{ vars.SMPT_SERVER }}
      SMPT_PORT: ${{ vars.SMPT_PORT }}
      SMPT_USER: ${{ vars.SMPT_USER }}
      SMPT_PASS: ${{ secrets.SMPT_PASS }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NODE_ENV: ${{ vars.NODE_ENV }} 
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd TribeBackend
          npm install
          npm run build --if-present
          npm run test --if-present
          echo "HOST=${{ vars.HOST }}"
          echo "SMPT_SERVER=${{ vars.SMPT_SERVER }}"
          echo "SMPT_PORT=${{ vars.SMPT_PORT }}"
          echo "SMPT_USER=${{ vars.SMPT_USER }}"
          echo "SMPT_PASS=${{ secrets.SMPT_PASS }}"
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}"
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}"
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}"
          echo "NODE_ENV=${{ vars.NODE_ENV }}"
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
      
      - name: Zip TribeBackend for deployment
        run: |
          Compress-Archive -Path TribeBackend/* -DestinationPath TribeBackend.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: TribeBackend.zip

  deploy-server:
    runs-on: windows-latest
    needs: build-server
    env:
      HOST: ${{ vars.HOST }}
      SMPT_SERVER: ${{ vars.SMPT_SERVER }}
      SMPT_PORT: ${{ vars.SMPT_PORT }}
      SMPT_USER: ${{ vars.SMPT_USER }}
      SMPT_PASS: ${{ secrets.SMPT_PASS }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }} 
      NODE_ENV: ${{ vars.NODE_ENV }} 
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_PRODUCTION }}
          github_deployment: true 
          deployment_environment: 'production'
          github_token: ${{ secrets.TRIBE_GITHUB_TOKEN }}

  build-android:
    runs-on: windows-latest
    env:
      APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
      APP_NAME: ${{ vars.APP_NAME }}
      UPLOAD_FILE: ${{ vars.UPLOAD_FILE }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: |
          cd TribeFrontend
          npm install

      - name: Build Android app
        run: |
          cd TribeFrontend/android
          ./gradlew assembleDebug

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          file: ${{ env.UPLOAD_FILE }}
          group: 'collaborators'
          notifyTesters: false
          debug: false