# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tribe-redmedia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      HOST: ${{ vars.HOST }}
      SMPT_SERVER: ${{ vars.SMPT_SERVER }}
      SMPT_PORT: ${{ vars.SMPT_PORT }}
      SMPT_USER: ${{ vars.SMPT_USER }}
      SMPT_PASS: ${{ secrets.SMPT_PASS }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}  
      NODE_ENV: ${{ vars.NODE_ENV }} 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd TribeBackend
          npm install
          npm run build --if-present
          npm run test --if-present
          echo "HOST=${{ vars.HOST }}"
          echo "SMPT_SERVER=${{ vars.SMPT_SERVER }}"
          echo "SMPT_PORT=${{ vars.SMPT_PORT }}"
          echo "SMPT_USER=${{ vars.SMPT_USER }}"
          echo "SMPT_PASS=${{ secrets.SMPT_PASS }}"
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}"
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}"
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}"
          echo "NODE_ENV=${{ vars.NODE_ENV }}"
      
      - name: Zip TribeBackend for deployment
        run: |
          Compress-Archive -Path TribeBackend/* -DestinationPath TribeBackend.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: TribeBackend.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    env:
      HOST: ${{ vars.HOST }}
      SMPT_SERVER: ${{ vars.SMPT_SERVER }}
      SMPT_PORT: ${{ vars.SMPT_PORT }}
      SMPT_USER: ${{ vars.SMPT_USER }}
      SMPT_PASS: ${{ secrets.SMPT_PASS }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NODE_ENV: ${{ vars.NODE_ENV }} 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72B604568D2641DF92C8B8E8FA0F42C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3684328871E64D6BA3A732F38F5E6E5C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35A913709129438AAE64926A5BA316AA }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tribe-redmedia'
          slot-name: 'Production'
          package: TribeBackend.zip
          